# -*- coding: utf-8 -*-
"""A3_prot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DncDthwvycpqhvVhbrPxmPwuvp54CLvk

Preparação e limpeza dos dados
"""

import pandas as pd
import matplotlib.pyplot as plt
import warnings
from sklearn.exceptions import UndefinedMetricWarning
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report

from google.colab import drive
import os
drive.mount('/content/drive')

caminho_arquivo = '/content/drive/MyDrive/Video_Games_Sales_as_at_22_Dec_2016.csv'

df = pd.read_csv(caminho_arquivo)

# Limpeza inicial:
df = df.dropna(subset=['Critic_Score', 'Rating'])

# Criar o Target (Bom, Médio, Ruim)
def categorizar_nota(nota):
    if nota >= 75: return 'Bom'
    elif nota >= 50: return 'Medio'
    else: return 'Ruim'

df['Target'] = df['Critic_Score'].apply(categorizar_nota)

# Preenchendo valores vazios antes de selecionar
df['Year_of_Release'] = df['Year_of_Release'].fillna(df['Year_of_Release'].median())
df['Global_Sales'] = df['Global_Sales'].fillna(0)

# Seleção de Atributos e One-Hot Encoding
# Usamos Plataforma, Gênero e Rating para prever a qualidade do jogo
X = df[['Platform', 'Genre', 'Rating', 'Year_of_Release', 'Global_Sales']]
X = pd.get_dummies(X)
y = df['Target']

# Separa 80% para a IA estudar e 20% para a prova final
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Base de Dados Pronta! Treinando com {len(X_train)} jogos e testando com {len(X_test)}.\n")

"""Criação dos modelos e do Comitê"""

# Criando os modelos individuais
modelo_knn = KNeighborsClassifier(n_neighbors=5)
modelo_arvore = DecisionTreeClassifier(max_depth=None, random_state=42, class_weight='balanced')
modelo_rf = RandomForestClassifier(n_estimators=150, max_depth=None, min_samples_split=10, random_state=42, class_weight='balanced')

# O Comitê junta os três e decide na votação
comite = VotingClassifier(
    estimators=[('KNN', modelo_knn), ('Arvore', modelo_arvore), ('RandomForest', modelo_rf)],
    voting='hard'
)

# Treinando o comitê
comite.fit(X_train, y_train)
print("Comitê treinado com sucesso!")

"""Treinamento e avaliação individual"""

modelos = [
    ('KNN', modelo_knn),
    ('Árvore de Decisão', modelo_arvore),
    ('Random Forest', modelo_rf),
    ('COMITÊ (Ensemble)', comite)
]

placar_final = []
print("=== PLACAR DE AVALIAÇÃO DOS MODELOS ===\n")

for nome, mod in modelos:
    mod.fit(X_train, y_train) # Treino
    preds = mod.predict(X_test) # Prova

    # Cálculo de acurácia
    acertos = (preds == y_test).sum()
    acuracia = (acertos / len(y_test)) * 100

    # Armazenando a acurácia para a sua tabela anterior
    placar_final.append({
        'Modelo': nome,
        'Acurácia (%)': f"{acuracia:.2f}%"
    })

    # Exibição do relatório detalhado por modelo
    print(f"\n{'='*10} RELATÓRIO DETALHADO: {nome} {'='*10}")
    print(classification_report(y_test, preds))

# Mostra a tabela comparativa resumida
print("\n=== RESUMO DA ACURÁCIA ===")
df_placar = pd.DataFrame(placar_final)
print(df_placar.to_string(index=False))
print("\n" + "="*45 + "\n")

"""Visualizações finais"""

# Gráfico 1: Matriz de Confusão do Comitê
preds_comite = comite.predict(X_test)
cm = confusion_matrix(y_test, preds_comite, labels=['Bom', 'Medio', 'Ruim'])

plt.figure(figsize=(8,6))
cm = confusion_matrix(y_test, comite.predict(X_test), labels=['Bom', 'Medio', 'Ruim'])
ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Bom', 'Medio', 'Ruim']).plot(cmap='Blues')
plt.title("Matriz de Confusão")
plt.show()